#!/bin/bash

# reference: https://www.marksanborn.net/howto/wiping-a-hard-drive-with-dd/
if [ "$1" == "" ]; then
	echo "usage: cleanDisk </dev/sdx>"
else
	# get root rights
	echo -n "Please enter password for sudo rights: "
	read -s pass
	echo ""

	echo "clean disk using /dev/zero"
	echo $pass | sudo -S dd if=/dev/zero of=$1 bs=1024 status=progress

	echo "clean disk using /dev/urandom 3 times"
	echo $pass | sudo -S dd if=/dev/urandom of=$1 bs=1024 status=progress
	echo $pass | sudo -S dd if=/dev/urandom of=$1 bs=1024 status=progress
	echo $pass | sudo -S dd if=/dev/urandom of=$1 bs=1024 status=progress

	echo done
fi

